name: wheather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.4.0
  provider: ^6.1.5
  lottie: ^3.3.1
  intl: ^0.20.2
  weather_animation: ^1.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cloudy.json
    - assets/rain.json
    - assets/snowfall.json
    - assets/sunny.json